apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno
    version: 3.2.6
    releaseName: kyverno
    namespace: kyverno
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - policies/pod-security-restricted.yaml
  - policies/require-signed-images.yaml
  - policies/require-sbom-attestation.yaml
  - policies/disallow-latest-tag.yaml
  - policies/require-resource-limits.yaml
  - policies/require-probes.yaml
  - policies/disallow-default-namespace.yaml
  - policies/restrict-image-registries.yaml
  - policies/require-labels.yaml
